### PR TITLE
Fix various visual and technical issues

### PR DESCRIPTION
**Pull request by d2s**
I did spend few hours learning the (overly complex) site structure,
and tried my best to do following fixes to the site.

### fix(speakers) fix broken image links

- Fix broken image links to speakers' latest Twitter profile pictures.

### style(CSS) improve readability of Sass files

- Improve readability of the Sass files.

### fix(CSS) correct size for missing images

- Adjust styles to work even in a situation where volunteer's profile image is missing.

### fix(footer) typographic change

- Correct capitalization of the product name.

### docs(README.md) update install instructions

- Update install instructions with more details.
- Add mention of how to install the Gemfile bundle.
- Improve document structure with a proper Markdown syntax.

### fix(Gemfile) rename GEMFILE to Gemfile

- Fix file name of Gemfile from broken GEMFILE name.
- Old name was not working when used on a Linux system.
- Now it is possible to install required gems with `bundle install` again.

### CODE REVIEW

**Comment by rinkkasatiainen** [comment]
Thanks! It surely has  a structure that one needs to know, in order to be able to modify it.
Thank you for the feedback that it appears to be overly complex - and in there I see an opportunity for me to learn - perhaps even together. 
Since for me, feedback from people is a key ingredient in learning - so: would you be willing to share you thoughts with me one day, regarding the site structure?

**Comment by d2s** [comment]
@rinkkasatiainen Short list of first thoughts:

### Directory structure

Main problem was the amount of places for similar items.
`/pages/` -directory should only be used for the site content, not for any visual styles.

There is "main" site structure at the [`/styles`](https://github.com/EuropeanTestingConference/europeantestingconference/tree/gh-pages/styles) -directory,
and year-based Sass structure under the [`/pages/2017/styles`](https://github.com/EuropeanTestingConference/europeantestingconference/tree/gh-pages/pages/2017/styles) -directory.

At the moment, there are multiple conflicting hierarchies for similar content, as  [`/styles/_snippets/2016/`](https://github.com/EuropeanTestingConference/europeantestingconference/tree/gh-pages/styles/_snippets/2016) -directory also contains things that are similar to what are present in [`/pages/2016/styles/sass/`](https://github.com/EuropeanTestingConference/europeantestingconference/tree/gh-pages/pages/2016/styles/sass) -directory.

There are also a lot of unneeded files in the `/pages/2017/styles/sass/` -directory that belong to a copy of boilerplate `bootstrap-sass` Git repository. That also includes automated tests of that project, and a lot of other files not related to the conference website. Might make sense to have some 'vendor' -type of directory somewhere, but even then, `_sponsors.scss` & `_topics.scss` should _not_ be on there, as site-specific files belong to elsewhere.


### Speaker / contributor images

Another problem is that all of the speaker and contributor profile pictures are direct links to Twitter etc. That causes the site break up every time someone changes their profile photo. Also, if someone loses control of their Twitter account, any subsequent profile photo will be instantly visible on the official website of the event. (_EDIT:_ actually, picture change would only mean that images break, not that there would be any extra content.) That creates both extra administration task (need to monitor profile pictures for changes), compared to more standard way of having conference speaker pictures under `/images/` -directory (similar to how sponsor logos are stored).


### Sass syntax

One thing that made the Sass files much more complex to look at was the mixed syntax with odd line break positions.

```
.left
{
    float: left;
}

.right
{
    float: right;
}
```

Individual styles are not the problem, but the amount of extra lines it creates. If the point of extra line break is to highlight potentially missing curly brace, that might not make sense as text editors do highlight the scope of individual selector's styles.

Still, some of the other styles use more traditional visual style:
```
.sponsor img {
    height: 64px;
}
```

Maybe it is just the way how most of the styles are written elsewhere. I understand that the current structure is probably similar to how some people write Java, but different languages have different visual styles of writing.

CSS Guidelines has a good description of more readable [Anatomy of a Ruleset](http://cssguidelin.es/#anatomy-of-a-ruleset), based on guidebook author [Harry Robert](http://csswizardry.com/)'s experiences working with some of the largest websites in the planet.

There is also [Sass Guidelines](https://sass-guidelin.es/), adaptation of it meant for Sass users, though some of the recommendations might not be as simple. Various other Sass & CSS structure styles exist, but those two have a lot of good things in them.


### Speed issues with Jekyll

Not exactly sure why, but the site generation process with `bundle exec jekyll serve --watch` is taking a lot of time. Tried to enable partial building of the site with `bundle exec jekyll serve --watch --incremental` extra flag, but it did not make any real difference to the actual speed of the site build process.

One of the reasons might be related to amount of extra files in the `/pages/` that could cause Jekyll to check unneeded amount of extra things every time something changes.


#### CSS generation issues

Not exactly sure what caused them, but often could not see the changes made to Sass files (even after I restarted the jekyll build process, and had Chrome Developer Console open, with cache disabled). Slow build speed could be one partial reason, but that does not explain all of it.


#### Potential for other site generator

Jekyll can be faster, I am sure, since have seen many using it. Still, another option could be to use some faster tool for future sites, if possible. One good alternative is [Hugo](http://gohugo.io/overview/introduction/), written in Go, that has much faster build times (~1 ms per page). It does support [import from Jekyll](http://gohugo.io/commands/hugo_import_jekyll/) and there are also some [extra notes](http://gohugo.io/tutorials/migrate-from-jekyll/) if one has a lot of custom Jekyll things.

---

Anyway, hopefully these notes can help to pinpoint some of the potential issues that make working with the current site feel a bit painful. Mainly these are caused by the lack of short documentation about site structure, though it feels that there is a lot of unneeded complexity in the current implementation.

**Comment by rinkkasatiainen** [comment]
Thanks for the reply!
 
If you are coming to European Testing Conference, I’d love to buy you a coffee / beer / something similar. I thank you so much for the thoroughness of your reply. This is a very good way to learn.

I’ll describe (the only) design decision we made and some designs we choose not to take.

**Directory Structure**
This was our only design decision - we wanted an easy way to create a new year - so that we could basically just copy the contents, remove stuff schedule, topics and speakers and all would be visible. Also, we wanted a way to modify year-by-year the layout (and CSS) so that the old years could remain the same.

We had at least 2 options.

 * to have all under one directory - namely ‘pages’.
 * to have the actual pages under one directory - namely ‘pages’ and snippets (the way we are clue sections to each individual page as Jekyll collection, namely _snippets and similarly for styles - to have them under styles/<year>

Typically, basically in all other Github-hosted web sites, I’ve chosen the latter. This time, though, we chose to experiment with the former with one goal in our minds - easy way to create new years.

This decision had one major drawback - which is the build time. I think Jekyll builds a separate page for each of the individual files located in 'pages' directory. It's not exactly what I've had in my mind - but the pain hasn't been big enough (yet) for me to solve it. I believe we'll discuss decision this with other folks, thanks to your comments!


**SASS**
Thank you for the idea of a ‘vendor’ type of directory. We’ll surely take and use that. 
And the syntax and link - I want to say only one thing: Thank You!

**Speaker images** 
Yes, you are totally right. I’ve been thinking also to have a Amazon S3 where I could put the images - if I didn’t want to put those to github. So far, the pain has not been big enough for me to actually make this happen.

**Comment by d2s** [comment]
@rinkkasatiainen Try out http://surge.sh/ for static asset hosting. Might work nicely for smaller site. Have been using it for few small projects so far. Easy, fast, & free for basics. (And no need to struggle with Amazon S3 buckets…)

I will most likely be at the European Testing Conference, so hopefully we meet there.

**Pull request merged**
